services:

  paddle-ocr:

    build: .
    
    container_name: paddle-ocr-server

    ports:
      - "8000:8000"

    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./models:/root/.paddlex
      - ./logs:/app/logs

    environment:
      - WATCHFILES_FORCE_POLLING=true

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app --reload-include "*.py"

    restart: unless-stopped